language: python
python:
  - "2.7"

services:
  - docker
install:
 - pip install -r test-requirements.txt

script:
    - git fetch origin master:master
    - git diff `git merge-base HEAD master`
    #    - docker pull docker.mycroft.ai/skills-tester
    #    - export NEW_SKILL = $( git diff `git merge-base HEAD master` .gitmodules | grep "^\+.*url" | sed 's/.*url *= *//' )
    #    - docker run skill-tests:latest ./test_skill.sh $NEW_SKILL
# Disable PEP8 testing for now, since existing skills don't pass.
# Should re-enable as part of 18.02
# - pep8 skill-*/*.py
